export const LOAD_LOGS_SUCCESS = "LOAD_LOGS_SUCCESS";
export const LOAD_TASKS_SUCCESS = "LOAD_TASKS_SUCCESS";
export const RUN_TASK_SUCCESS = "RUN_TASK_SUCCESS";
export const LOAD_RESULTS_SUCCESS = "LOAD_RESULTS_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
